require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

desc ".rbファイル作成 + スペック作成"
task :new_rb, :name do |t, args|
  p args[:name]
  sh "code lib/#{args.name}.rb spec/#{args.name}_spec.rb"
end
